name: Go Test and Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.19.0-bullseye
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Test
      run: go test -v ./...
  build:
    strategy:
      matrix:
        goarch: [amd64, arm64]
        goos: [linux, darwin,windows]
    runs-on: ubuntu-latest
    container: golang:1.19.0-bullseye
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        LDFLAGS: -X main.Version=${{ github.ref }} -X main.Build=${{ github.run_id }}
      run: go build -v -ldflags="${LDFLAGS}" ./...

